import Head from 'next/head'
import Image from 'next/image'
import Content from '../component/Content'
import Food from '../component/Food'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Food App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content/>
      <Food/>
    </div>
  )
}
